### ISSUE TITLE
Optimize the tokens by removing whitespace

### ISSUE THREAD

**Issue by TimPietrusky** [failfa-st/fail1#5]

**Comment by pixelass** [comment]
It is crucial that comments remain untouched and the minifier supports esm. We have a custom prototype which works (with flaws). The removal of whitespaces has a big impact since each white space counts as a separate token. We also need the responses to follow those rules, which requires some adjustments to our system message.

The limit is 4096 token (user + assistant) e.g. user uses 1000 tokens, then the assistant can use the remaining ~3000 tokens.
